// A profile exactly as the app writes it (ProfileCodec.encode).
export function validProfile(overrides = {}) {
  return {
    name: 'Sam',
    nativeLanguage: 'English',
    currentLevel: 'a1',
    targetLevel: 'b1',
    goal: 'goethe',
    currentLessonId: 'a1_articles',
    lessonProgress: {
      a1_articles: { status: 'completed', attempts: 1, bestCorrect: 4, total: 5 },
    },
    skillStats: { definite_articles: { attempts: 5, correct: 4 } },
    exerciseStats: {},
    kindStats: {},
    areaStats: {},
    flashcards: { day: '2026-10-08', newToday: 3, states: {} },
    gamification: {
      badges: {},
      questProgress: {},
      questsDone: [],
      gameBest: {},
      gamesPlayed: 0,
    },
    recentMistakes: [],
    reviewItems: [],
    scores: { vocabulary: 0.5, grammar: 0.5, reading: 0, listening: 0, writing: 0, speaking: 0 },
    xp: 120,
    streak: 3,
    dailyGoalMinutes: 15,
    preferredTopics: ['Travel'],
    focusSkills: ['Speaking'],
    appearancePreference: 'system',
    surfaceStyle: 'glass',
    glassIntensity: 60,
    aiProviderPreference: 'automatic',
    aiModel: 'Qwen',
    voice: 'de_DE-thorsten-medium',
    speechRate: 170,
    voicePauseMs: 1200,
    advancedAiControls: false,
    lessonRemindersEnabled: false,
    reviewRemindersEnabled: false,
    streakRemindersEnabled: false,
    ...overrides,
  };
}
