import 'package:flutter/material.dart';
import 'package:lottie/lottie.dart';

/// One of Sprichst's Lottie animations (`assets/lottie/<name>_light|dark.json`,
/// generated by `tool/lottie/gen_lottie.py`), in the file that matches the
/// current theme.
///
/// The animation is decoration: the words beside it carry the meaning, so it is
/// hidden from screen readers. When the system asks for reduced motion it does
/// not play and shows [stillAt] instead (the finished picture for one-shot
/// animations; a point where everything is visible for loops).
class SprichstLottie extends StatelessWidget {
  const SprichstLottie(
    this.name, {
    super.key,
    this.width,
    this.height,
    this.repeat = false,
    this.stillAt = 1,
  });

  final String name;
  final double? width;
  final double? height;
  final bool repeat;

  /// Which moment (0 to 1) to show when motion is reduced.
  final double stillAt;

  static String assetOf(String name, Brightness brightness) =>
      'assets/lottie/${name}_${brightness == Brightness.dark ? 'dark' : 'light'}.json';

  @override
  Widget build(BuildContext context) {
    final still = MediaQuery.disableAnimationsOf(context);
    return ExcludeSemantics(
      child: Lottie.asset(
        assetOf(name, Theme.of(context).brightness),
        width: width,
        height: height,
        fit: BoxFit.contain,
        repeat: repeat,
        controller: still ? AlwaysStoppedAnimation<double>(stillAt) : null,
        // A missing or broken file leaves a gap, never a red error box.
        errorBuilder: (_, __, ___) => SizedBox(width: width, height: height),
      ),
    );
  }
}
